version: '3'

networks:
  minio_network:

services:
  minio:
    container_name: minio
    image: bitnami/minio:latest
    volumes:
      - "~/tempMinio:/data"
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - minio_network
    restart: always
    environment:
      MINIO_ROOT_USER: "admin123"
      MINIO_ROOT_PASSWORD: "admin123"
